ALTER TABLE public.banners
  ADD COLUMN IF NOT EXISTS heading_text text DEFAULT 'Adorn Your Story',
  ADD COLUMN IF NOT EXISTS heading_font_family text DEFAULT 'Playfair Display',
  ADD COLUMN IF NOT EXISTS heading_font_size_mobile integer DEFAULT 28,
  ADD COLUMN IF NOT EXISTS heading_font_size_desktop integer DEFAULT 48,
  ADD COLUMN IF NOT EXISTS heading_font_weight text DEFAULT 'bold',
  ADD COLUMN IF NOT EXISTS heading_italic boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS heading_uppercase boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS heading_letter_spacing numeric DEFAULT 0,
  ADD COLUMN IF NOT EXISTS heading_line_height numeric DEFAULT 1.2,
  ADD COLUMN IF NOT EXISTS heading_color text DEFAULT '#FFFFFF',
  ADD COLUMN IF NOT EXISTS heading_opacity integer DEFAULT 100,
  ADD COLUMN IF NOT EXISTS subheading_text text,
  ADD COLUMN IF NOT EXISTS subheading_font_family text DEFAULT 'Inter',
  ADD COLUMN IF NOT EXISTS subheading_font_size_mobile integer DEFAULT 14,
  ADD COLUMN IF NOT EXISTS subheading_font_size_desktop integer DEFAULT 18,
  ADD COLUMN IF NOT EXISTS subheading_font_weight text DEFAULT 'normal',
  ADD COLUMN IF NOT EXISTS subheading_italic boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS subheading_uppercase boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS subheading_letter_spacing numeric DEFAULT 0,
  ADD COLUMN IF NOT EXISTS subheading_color text DEFAULT '#FFFFFF',
  ADD COLUMN IF NOT EXISTS subheading_opacity integer DEFAULT 85,
  ADD COLUMN IF NOT EXISTS content_h_align text DEFAULT 'left',
  ADD COLUMN IF NOT EXISTS content_v_align text DEFAULT 'center',
  ADD COLUMN IF NOT EXISTS content_padding_x integer DEFAULT 24,
  ADD COLUMN IF NOT EXISTS content_padding_y integer DEFAULT 32,
  ADD COLUMN IF NOT EXISTS content_max_width integer DEFAULT 560,
  ADD COLUMN IF NOT EXISTS btn_visible boolean DEFAULT true,
  ADD COLUMN IF NOT EXISTS btn_text text DEFAULT 'Shop Now',
  ADD COLUMN IF NOT EXISTS btn_url text DEFAULT '/catalogue',
  ADD COLUMN IF NOT EXISTS btn_bg_color text DEFAULT '#C9A84C',
  ADD COLUMN IF NOT EXISTS btn_text_color text DEFAULT '#FFFFFF',
  ADD COLUMN IF NOT EXISTS btn_border_color text DEFAULT 'transparent',
  ADD COLUMN IF NOT EXISTS btn_border_width integer DEFAULT 0,
  ADD COLUMN IF NOT EXISTS btn_border_radius integer DEFAULT 50,
  ADD COLUMN IF NOT EXISTS btn_font_size integer DEFAULT 14,
  ADD COLUMN IF NOT EXISTS btn_font_weight text DEFAULT 'semibold',
  ADD COLUMN IF NOT EXISTS btn_italic boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS btn_letter_spacing numeric DEFAULT 0,
  ADD COLUMN IF NOT EXISTS btn_padding_x integer DEFAULT 28,
  ADD COLUMN IF NOT EXISTS btn_padding_y integer DEFAULT 14,
  ADD COLUMN IF NOT EXISTS btn_shadow boolean DEFAULT true,
  ADD COLUMN IF NOT EXISTS btn_align text DEFAULT 'left',
  ADD COLUMN IF NOT EXISTS btn_full_width_mobile boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS overlay_color text DEFAULT '#000000',
  ADD COLUMN IF NOT EXISTS overlay_gradient boolean DEFAULT true,
  ADD COLUMN IF NOT EXISTS bg_focal_x integer DEFAULT 50,
  ADD COLUMN IF NOT EXISTS bg_focal_y integer DEFAULT 50,
  ADD COLUMN IF NOT EXISTS height_mobile integer DEFAULT 420,
  ADD COLUMN IF NOT EXISTS height_desktop integer DEFAULT 580,
  ADD COLUMN IF NOT EXISTS autoplay_duration integer DEFAULT 5000,
  ADD COLUMN IF NOT EXISTS transition text DEFAULT 'fade';