ALTER TABLE public.settings
  ADD COLUMN IF NOT EXISTS card_border_radius integer DEFAULT 16,
  ADD COLUMN IF NOT EXISTS card_shadow text DEFAULT 'sm',
  ADD COLUMN IF NOT EXISTS card_border_color text DEFAULT '#EDE8E1',
  ADD COLUMN IF NOT EXISTS card_border_width integer DEFAULT 1,
  ADD COLUMN IF NOT EXISTS card_layout text DEFAULT 'grid',
  ADD COLUMN IF NOT EXISTS btn_border_radius integer DEFAULT 50,
  ADD COLUMN IF NOT EXISTS btn_primary_bg text DEFAULT '#C9A84C',
  ADD COLUMN IF NOT EXISTS btn_primary_text text DEFAULT '#FFFFFF',
  ADD COLUMN IF NOT EXISTS btn_secondary_bg text DEFAULT 'transparent',
  ADD COLUMN IF NOT EXISTS btn_secondary_text text DEFAULT '#C9A84C',
  ADD COLUMN IF NOT EXISTS btn_secondary_border text DEFAULT '#C9A84C',
  ADD COLUMN IF NOT EXISTS btn_font_weight text DEFAULT '600',
  ADD COLUMN IF NOT EXISTS btn_letter_spacing numeric DEFAULT 0,
  ADD COLUMN IF NOT EXISTS font_heading text DEFAULT 'Playfair Display',
  ADD COLUMN IF NOT EXISTS font_body text DEFAULT 'Inter',
  ADD COLUMN IF NOT EXISTS font_heading_url text,
  ADD COLUMN IF NOT EXISTS font_body_url text,
  ADD COLUMN IF NOT EXISTS font_size_base integer DEFAULT 16,
  ADD COLUMN IF NOT EXISTS line_height_base numeric DEFAULT 1.6,
  ADD COLUMN IF NOT EXISTS section_spacing integer DEFAULT 48,
  ADD COLUMN IF NOT EXISTS container_max integer DEFAULT 1280,
  ADD COLUMN IF NOT EXISTS product_grid_cols_mobile integer DEFAULT 2,
  ADD COLUMN IF NOT EXISTS product_grid_cols_tablet integer DEFAULT 3,
  ADD COLUMN IF NOT EXISTS product_grid_cols_desktop integer DEFAULT 4,
  ADD COLUMN IF NOT EXISTS seo_keywords text,
  ADD COLUMN IF NOT EXISTS seo_auto_generate boolean DEFAULT true,
  ADD COLUMN IF NOT EXISTS seo_brand_keywords text DEFAULT 'Eraya,artificial jewellery,imitation jewellery,fashion jewellery India',
  ADD COLUMN IF NOT EXISTS google_place_id text,
  ADD COLUMN IF NOT EXISTS google_reviews_visible boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS google_reviews_api_key text,
  ADD COLUMN IF NOT EXISTS policy_privacy_title text DEFAULT 'Privacy Policy',
  ADD COLUMN IF NOT EXISTS policy_privacy_body text DEFAULT 'We respect your privacy. Your personal information is never shared with third parties.',
  ADD COLUMN IF NOT EXISTS policy_terms_title text DEFAULT 'Terms of Service',
  ADD COLUMN IF NOT EXISTS policy_terms_body text DEFAULT 'By using Eraya, you agree to our terms of service.',
  ADD COLUMN IF NOT EXISTS custom_domain text,
  ADD COLUMN IF NOT EXISTS domain_verified boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS domain_verification_token text,
  ADD COLUMN IF NOT EXISTS packing_cost numeric DEFAULT 0,
  ADD COLUMN IF NOT EXISTS packing_cost_visible_to_admin boolean DEFAULT true,
  ADD COLUMN IF NOT EXISTS google_tag_manager_id text,
  ADD COLUMN IF NOT EXISTS enquiry_requires_login boolean DEFAULT true;

UPDATE public.settings SET
  shipping_free_above = COALESCE(shipping_free_above, shipping_free_min_order, 999),
  shipping_charge = COALESCE(shipping_charge, shipping_flat_cost, 99)
WHERE id = 1;